### ISSUE TITLE
Install issues on some kindles

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/flutter-blocks#28]
We loaded the apk on 5 kindles successfully, but on one it seemed to install, but when launched we just get a blank black screen. Reinstall etc didn’t work to fix it. We used the same file and process for installing on all. Not sure what was going on. As far as I know they are the same version of kindle.

**Comment by ehamner** [comment]
Kindle "Flutter 15" left with Terence for testing.

**Comment by tsun1215** [comment]
**Flutter 15:** Fixed
- Was running an OS that was 1 year older than the Fire Blue
- Bug was because the webview running was older and did not support some features
- Fix: Built in backwards compatibility into the app

**Fire Blue:** Hardware Issue
- Determined that the touchscreen has problems: When the "Pointer Location" debug setting on the tablet was turned on, you can see that the tablet very often registers clicks as movements (see dx and dx debugging outputs). Additionally, no matter the type of touch, it always thinks that the touch size is 0.20. When doing the same test on other Fire tablets (2), click clearly show that dx=dy=0 and the size goes to 0.0 when nothing is touching the screen.
- Won't fix
